import './style.css'
const num1 = Number(prompt('enter your first number'))
const num2 = Number(prompt('enter your second number'))
const pi = (3.14159265358979)
const addition = (num1 + num2)
console.log(addition)
const subtraction = (num1 - num2)
console.log(subtraction)
const multiplication = (num1 * num2)
console.log(multiplication)
const division = (num1 / num2)
console.log(division)
const exponent1 = (num1*num1)
console.log(exponent1)
const exponent2 = (num2*num2)
console.log(exponent2)
const sinstep1 = (16 * num1)
const sinstep2 = (pi - num1)
const sinstep3 = (5* pi * pi)
const sinstep4 = (4 * num1)
const sinstep5 = (pi-num1)
const sinstep6 = (sinstep1 * sinstep2)
const sinstep7 = (sinstep3 - (sinstep4 * sinstep5))
const sin1 = sinstep6/sinstep7
console.log(sin1)